version: "3.7"

services:
  strapi:
    image: node:latest
    ports:
      - 1337:1337
    volumes:
      - ./strapi:/usr/local/app
    depends_on:
      - db
    restart: always
    working_dir: /usr/local/app
    entrypoint: "/bin/bash"
    command: '-c "if [ ! -d "node_modules" ]; then npm i; fi; npm run develop"'
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      DATABASE_HOST: db

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432

    volumes:
      - ./postgres:/var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      PGDATA: /var/lib/postgresql/data

  client:
    image: node:latest
    environment:
      STRAPI_API_TOKEN: "${STRAPI_API_TOKEN}"
      STRAPI_URI: "${STRAPI_URI}"
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/local/app
    restart: always
    working_dir: /usr/local/app
    entrypoint: "/bin/bash"
    command: '-c "if [ ! -d "node_modules" ]; then npm i; fi; npm run develop"'
